<aura:application>
<c:Comienzo></c:Comienzo>
<c:contador></c:contador>
<c:contador></c:contador>
<c:contador></c:contador>
<c:contador></c:contador>
<c:contador></c:contador>
<c:contador></c:contador>
<c:contador></c:contador>
<c:contador></c:contador>
<c:contador></c:contador>
<c:contador></c:contador>
</aura:application>	
